# arguments for dataset
dataset: Med
nclass: 2
crop_size: 321
data_root: /home/yea0826/dataset/Med/

# arguments for training
epochs: 160
batch_size: 8 # per GPU x 4 GPUs
lr: 0.001
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet50
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
